export enum ECrypto {
  AUR = 'Auroracoin',
  BCH = 'Bitcoin Cash',
  BTC = 'Bitcoin',
  DASH = 'Dash',
  DOGE = 'Dogecoin',
  ETC = 'Ethereum Classic',
  ETH = 'Ethereum',
  GRC = 'Gridcoin',
  LTC = 'Litecoin',
  MZC = 'Mazacoin',
  Nano = 'Nano',
  NEO = 'Neo',
  NMC = 'Namecoin',
  Nxt = 'NXT',
  POT = 'PotCoin',
  PPC = 'Peercoin',
  TIT = 'Titcoin',
  USDC = 'USD Coin (stablecoin)',
  USDT = 'Tether (stablecoin)',
  XLM = 'Stellar',
  XMR = 'Monero',
  XRP = 'Ripple',
}
