export enum EExchange {
  COINBASE = 'Coinbase',
  FTX = 'FTX',
  // Delete
  // COINBASE1 = 'Coinbase',
  // _FTX = 'FTX',
  // _COINBASE = 'Coinbase',
  // __FTX = 'FTX',
  // __COINBASE = 'Coinbase',
  // ___FTX = 'FTX',
  // ___COINBASE = 'Coinbase',
  // ____FTX = 'FTX',
  // ____COINBASE = 'Coinbase',
  // _____FTX = 'FTX',
  // ______COINBASE = 'Coinbase',
  // F_TX = 'FTX',
  // CO_INBASE = 'Coinbase',
  // FTX_ = 'FTX',
  // COIN__BASE = 'Coinbase',
  // F__TX = 'FTX',
  // COI_NBASE = 'Coinbase',
  // F___TX = 'FTX',
  // COIN_BASE = 'Coinbase',
}
